version: '3.8'

services:



    electronicstore:
        build: onlineelectronic
        ports:
        - 4441:4441



    postgres:
        image: postgres:14.5
        ports:
        - 5432:5432

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pgadmin
            POSTGRES_DB: electronicdb
